# The blog configuration

name: SmarteX
description: Heveicultura de Precisão
author: Hans Bonini
permalink: /:title/
timezone: America/Sao_Paulo

# contatos do site
contacts:
  email: atendimento@smartex.com.br
  twitter: smartex
  youtube: smartex
  facebook: smartex
  instagram: smartex

# url padrão do site

url: http://smartex.agr.br
baseurl: ""

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
