# Configuração do Site
name: SmarteX
description: Heveicultura de Precisão
author: Hans Bonini
permalink: /:title/
timezone: America/Sao_Paulo

# contatos do site
email: atendimento@smartex.com.br
twitter: smartex
youtube: smartex
facebook: smartex
instagram: smartex

# url padrão do site
url: http://smartex.agr.br
